[project]
name = "trace-deidentifier"
version = "0.2.0"
description = "xAPI trace deidentication"
authors = [
    { name = "Pierre", email = "pierre.martel@inokufu.com" }
]
dependencies = [
    "fastapi>=0.115.14,<0.115.15",
    "uvicorn[standard]>=0.35.0,<0.35.1",
    "ralph-malph>=5.0.1,<5.1.0",
    "httpx>=0.28.1,<0.28.2",
    "gunicorn>=23.0.0,<23.1.0",
    "logger @ git+https://github.com/inokufu/python-logger@v0.2.1",
    "configcore @ git+https://github.com/inokufu/python-config@v0.2.1",
]
readme = "README.md"
requires-python = ">= 3.14"


[dependency-groups]
dev = [
    "pytest>=9.0.2,<9.1.0",
    "pytest-asyncio>=1.3.0,<1.4.0",
    "pytest-cov>=7.0.0,<7.1.0",
    "ty>=0.0.5,<0.0.6",
]

[tool.uv]
add-bounds = "minor"
package = true

[project.scripts]
start = "trace_deidentifier.__main__:main"
test = "pytest:main"

[tool.ruff]
output-format = "concise"
target-version = "py314"
line-length = 88
indent-width = 4

lint.select = ["ALL"]
lint.ignore = [
  "PLE1205",  # logging-too-many-args
  "FBT",  # flake8-boolean-trap
  "E501",  # line-too-long
  "D100",  # pydocstyle,
  "ANN401",  # flake8-annotations
  "EM",  # flake8-errmsg
  "INP001",  # implicit-namespace-package
  "TRY003",  # raise-vanilla-args
  "TRY401",  # verbose-log-message
  "TC",  # Type checking
]
lint.extend-unfixable = [
  "TCH002",
  "TRY400",
  "SIM105",
]

lint.pydocstyle.convention = "pep257"
lint.flake8-bandit.check-typed-exception = true
lint.flake8-type-checking.strict = true

# Avoid error B008 for fastapi params
lint.flake8-bugbear.extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]

[tool.ruff.lint.extend-per-file-ignores]
# Avoid error S101 for assertions
"tests/*.py" = ["S101"]

[tool.pytest.ini_options]
addopts = "--cov=trace_deidentifier"

[tool.coverage.report]
exclude_lines = [
    "@abstractmethod"
]
